### ISSUE TITLE
HP<>MP Materia not capping max MP to 999?

### ISSUE THREAD

**Issue by maciej-trebacz** [dangarfield/ff7-fenrir#1]
I was reading the source code implementing HP<>MP materia:

https://github.com/dangarfield/ff7-fenrir/blob/master/app/battle/battle-stats.js#L228

And I think you've missed the case here where the Max HP is more than 999. So before applying you could have:

HP: 2000
MP: 500

After the swap you should have:

HP: 500
MP: 999

But the code misses a check to cap the MP at 999 it seems.

**Comment by dangarfield** [comment]
I _believe_ this is ok.

There is a check in https://github.com/dangarfield/ff7-fenrir/blob/master/app/battle/battle-stats.js#L219 and https://github.com/dangarfield/ff7-fenrir/blob/master/app/battle/battle-stats.js#L226 to get the _correct_ values (the values are min/max/trunc'd there). The line 228+ just swaps them.

After testing with high base hp/mp (9000,900) with a maxed hp plus and mp plus materia I get (without HP<->MP):

![image](https://user-images.githubusercontent.com/4086513/140782800-ee852cea-b308-462e-846c-1a63ab57cf4e.png)

and with HP<->MP:

![image](https://user-images.githubusercontent.com/4086513/140782705-9f646132-1603-479c-a73a-aefa0766d55f.png)

But, this is still just a very iterative process and I'm happy to be pointed to the right behaviour!

**Current tasks**: I'm gradually just working through the menus and kujata (kernel) data. There are a lot of behaviours that I hadn't noticed before regarding the application of stats and stil stuff to do (materia / equip affecting steal rates, gil, exp etc), so yep, any advice or wrong areas pointed out is great!

To reproduce, set the **debugSetEquipmentAndMateria** function in https://github.com/dangarfield/ff7-fenrir/blob/master/app/battle/battle-stats.js#L415 to:
```js
window.data.savemap.characters.Cloud.stats.hp.base = 9000
window.data.savemap.characters.Cloud.stats.mp.base = 900

setEquipmentAndMateriaForTesting(
  window.data.savemap.characters.Cloud,
  'Ultima Weapon', 'Escort Guard', '',
  ['', ''],
  ['HP Plus', 'MP Plus', ''] // or ['HP Plus', 'MP Plus', 'HP<->MP']
)
```

**Comment by maciej-trebacz** [comment]
Yeah I noticed there are initial checks to cap HP and MP to 9999 and 999 respectively, but that check should probably be applied again after the swap, so you don't end up with more than 999 MP.

**Comment by maciej-trebacz** [comment]
Btw this project is really cool and I'm very surprised how far you've gone with it. Seeing FF7 intro and then the actual game rendered in the browser is awesome.

I'm currently working on tools to decompile and edit FF7 worldmap data (walkmesh & scripts). My tools are written in Typescript. When that project is in a releasable state I'll make sure to ping you, as that might interest you :)

**Comment by dangarfield** [comment]
> Yeah I noticed there are initial checks to cap HP and MP to 9999 and 999 respectively, but that check should probably be applied again after the swap, so you don't end up with more than 999 MP.

Just to triple check. I'm certain the behaviour of HP<->MP **allows** you to have more than 999 MP, eg 9999 is the max MP. That's the whole point, right?

**Comment by maciej-trebacz** [comment]
> Just to triple check. I'm certain the behaviour of HP<->MP **allows** you to have more than 999 MP, eg 9999 is the max MP. That's the whole point, right?

You're totally right, for some reason I was convinced that it would still not allow you to break the 999 MP limit, but I've double checked and it does indeed allow you to do that, so I'm closing the issue. My bad, sorry.

**Comment by dangarfield** [comment]
No worries, thanks for having an interest! As always, I'm happy to learn both from a technical and game mechanics perspective!
